language: node_js
node_js:
  - '4'
  - '6'
jobs:
  include:
    - stage: deploy
      if: branch = master
      name: Release to npm
      script: npm run semantic-release
    - script: npm run coveralls
      name: Coveralls
